# Generated by Django 5.0.3 on 2024-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='status',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
