# Generated by Django 5.0.3 on 2024-06-23 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_api', '0002_alter_virtualmachine_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('RAM', models.PositiveIntegerField()),
                ('disk', models.PositiveBigIntegerField()),
                ('ip_address', models.CharField(max_length=48)),
                ('nbres_vm', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MicroVM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('os', models.CharField(max_length=48)),
                ('ip_address', models.CharField(max_length=48)),
                ('taille', models.PositiveBigIntegerField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm_api.serveur')),
            ],
        ),
    ]
