# Generated by Django 5.0.3 on 2024-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_api', '0003_serveur_microvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='microvm',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VirtualMachine',
        ),
    ]
